// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  
    
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4wegvKVBzWS50qkQcFY852qunT5BPV8c',
    appId: '1:1067526727745:web:e7dae4a55d307bc2a4fec0',
    messagingSenderId: '1067526727745',
    projectId: 'parcial-24ab8',
    authDomain: 'parcial-24ab8.firebaseapp.com',
    storageBucket: 'parcial-24ab8.firebasestorage.app',
    measurementId: 'G-NHM0NF4XWJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOZF897UeV1vThVriiIhpgc4ZaAGRJn8',
    appId: '1:1067526727745:ios:38d5efe1907b8d17a4fec0',
    messagingSenderId: '1067526727745',
    projectId: 'parcial-24ab8',
    storageBucket: 'parcial-24ab8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1XbwV-01czWxLdX65zgGnN5xSiHtiiBk',
    appId: '1:1067526727745:android:e14ca759436b15bfa4fec0',
    messagingSenderId: '1067526727745',
    projectId: 'parcial-24ab8',
    storageBucket: 'parcial-24ab8.firebasestorage.app',
  );
}
